2022-04-09 at 16:46:33

diff --git a/configs/bash_aliases b/configs/bash_aliases
--- a/configs/bash_aliases
+++ b/configs/bash_aliases
@@ -32,6 +32,7 @@ alias LT=lt
 alias rm='rm -i'
 alias cp='cp -i'
 alias mv='mv -i'
+alias \?='echo "\e[0;31m$(pwd)\e[0m"' # $'\e[0;31m$PWD\e[0m'
 
 # convenience aliases
 alias mkdir='mkdir -p'
@@ -63,6 +64,7 @@ alias search='history | grep'
 alias py='python'
 alias py3='python3'
 
+# more manageable peek at history
 alias history='history | less'
 
 
@@ -99,19 +101,16 @@ function weather() {
 # about directory operations.
 
 # 1. override cd to highlight current directory.
-function cd() {
-  builtin cd "$@" || return
-  printf "\n\033[0;32m%s\033[0m\n" "$(pwd)"
+function cd() { 
+  builtin cd "$@" > /dev/null && echo "\e[0;31m$(pwd)\e[0m"
 }
 # 2. override pushd to highlight current directory.
 function pushd() {
-  builtin pushd "$@" || return
-  printf "\n\033[0;32m%s\033[0m\n" "$(pwd)"
+  builtin pushd "$@" > /dev/null && echo "\e[0;31m$(pwd)\e[0m"
 }
 # 3. override popd to highlight current directory.
 function popd() {
-  builtin popd "$@" || return
-  printf "\n\033[0;32m%s\033[0m\n" "$(pwd)"
+  builtin popd "$@" > /dev/null && echo "\e[0;31m$(pwd)\e[0m"
 }
 
 # count the number of files in a directory.
@@ -323,4 +322,26 @@ function shifter() {
     done
   fi
   return 0
+}
+
+# See all ASCII color codes.
+function colors() {
+  usage="\tUsage: colors [--help] [--all] [color]\n\t[color] must be between 0 and 255."
+  if [[ $# -eq 0 || $1 == --help ]]; then
+    echo "${usage}"
+    return 0
+  elif [[ $1 == '--all' || $1 == '-a' ]]; then
+    for code in {0..255}; do
+      echo -e "\e[38;5;${code}m"'\\e[38;5;'"$code"m"\e[0m"
+    done
+    return 0
+  elif (( $1 < 0 )) || (( $1 > 255 )); then
+    echo "Error: invalid color code."
+    echo "${usage}"
+    return 1
+  else
+    declare -i code=$1
+    echo -e "\e[38;5;${code}m"'\\e[38;5;'"$code"m"\e[0m"
+  fi
+  return 0  
 }
